# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    branches:
      - master
      - beta
      - next

jobs:
  release:
    name: Check release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Install modules & build the Library
        run: |
          npm ci
          npm run build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/changelog@^5.0.1
            @semantic-release/git@^9.0.0
            @semantic-release/github@^7.2.3
            @semantic-release/npm@^7.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          NPM_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
